services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_APP_NAME: ${DB_APP_NAME}
      DB_APP_USER: ${DB_APP_USER}
      DB_APP_PASS: ${DB_APP_PASS}
    volumes:
      - "./database/data:/var/data/db"
  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_APP_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      SPRING_DATASOURCE_USERNAME: ${DB_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_APP_PASS}
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend