services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_APP_NAME: ${DB_APP_NAME}
      DB_APP_USER: ${DB_APP_USER}
      DB_APP_PASS: ${DB_APP_PASS}
    volumes:
      - "./database/data:/var/data/db"
    networks:
      - passkey-demo-backend
  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_APP_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      SPRING_DATASOURCE_USERNAME: ${DB_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_APP_PASS}
      WEBAUTHN_ORIGIN_URL: ${WEBAUTHN_ORIGIN_URL}
      WEBAUTHN_RP_ID: ${WEBAUTHN_RP_ID}
    networks:
      - passkey-demo-frontend
      - passkey-demo-backend
  frontend:
    build: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - passkey-demo-frontend
  cloudflare:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - passkey-demo-frontend
    depends_on:
      - frontend

networks:
  passkey-demo-frontend:
    driver: "bridge"
  passkey-demo-backend: